### PR TITLE
Revertch to json

### PR DESCRIPTION
**Pull request by mbdebian**
Revert Clickhouse feed to JSON format and update configuration context for 22.06 platform release.

### CODE REVIEW

**Comment by mbdebian** [comment]
Sorry with the Title, I meant **Revert To JSON**

**Comment by JarrodBaker** [comment]
Is there a file missing @mbdebian ? The changes are just updating version numbers and don't have anything to do with JSON as far as I can see?

**Comment by mbdebian** [comment]
> Is there a file missing @mbdebian ? The changes are just updating version numbers and don't have anything to do with JSON as far as I can see?

It could be because it's kind of a roll back from the changes on Clickhouse feed that were already merged

**Comment by mbdebian** [comment]
> Is there a file missing @mbdebian ? The changes are just updating version numbers and don't have anything to do with JSON as far as I can see?

I think it is safe to approve, and, if the changes to the Clickhouse script are not back to JSON, I can quickly fix that

**Pull request merged**
